version: '2'
services:
  redis:
    start_on_create: true
    ${scale}
    health_check:
      port: 6379
      interval: 30000
      unhealthy_threshold: 3
      healthy_threshold: 3
      response_timeout: 5000
      strategy: recreate
      request_line: ''